# Generated by Django 5.1 on 2024-10-30 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PdfDocument",
            fields=[
                (
                    "paper_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("detail", models.TextField()),
                ("summary", models.TextField()),
                ("pdf_url", models.URLField()),
                ("num_pages", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Highlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.IntegerField()),
                ("highlighted_text", models.TextField()),
                ("start_offset", models.IntegerField()),
                ("end_offset", models.IntegerField()),
                (
                    "pdf_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="main_app.pdfdocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlashCard",
            fields=[
                (
                    "flashcard_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TO_READ", "TO_READ"),
                            ("READING", "READING"),
                            ("UNDERSTAND", "UNDERSTAND"),
                            ("REVIEW", "REVIEW"),
                            ("KEY_POINT", "KEY_POINT"),
                            ("APPLY", "APPLY"),
                            ("TO_DISCUSS", "TO_DISCUSS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("highlight_by", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("ai_analysis", models.TextField(blank=True)),
                ("related_to", models.CharField(max_length=255)),
                ("feature_data", models.JSONField(blank=True, null=True)),
                (
                    "pdf_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcards",
                        to="main_app.pdfdocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "message_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "pdf_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="main_app.pdfdocument",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="main_app.user",
                    ),
                ),
            ],
        ),
    ]
