# Generated by Django 5.1 on 2024-10-30 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_remove_pdfdocument_pdf_url_pdfdocument_pdf_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="create_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
