# Generated by Django 5.1 on 2024-10-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_pdfdocument_create_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="related_to",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
